import 'package:url_launcher/url_launcher.dart';

class ClgNames{
  String firstname;
  String lastname;

  ClgNames({String this.firstname, String this.lastname});

  static List<ClgNames> getClgs(){
    return <ClgNames>[
      ClgNames(firstname: "A.D.Patel Institute Of Tech.,Karamsad", lastname: "http:adit.ac.in"),
      ClgNames(firstname: "ADANI INSTITUTE OF INFRASTRUCTURE ENGINEERING, AHMEDABAD", lastname: "http://www.aii.ac.in"),
      ClgNames(firstname: "ADITYA SILVER OAK INSTITUTE OF TECHNOLOGY (WITHIN LIMITS OF AHMEDABAD MUNICIPAL CORPORATION) AHMEDABAD", lastname: "http://asoit.edu.in/"),
      ClgNames(firstname: "Ahmedabad Institute Of Tech, Ahmedabad", lastname: "http://www.aitindia.in"),
      ClgNames(firstname: "Alpha College Of Engg. & Tech., Khatraj, Kalol", lastname: "http:alpha-cet.in"),
      ClgNames(firstname: "Amiraj College Of Engg & Tech., Sanand, Ahmedabad", lastname: "https://www.amirajcollege.in/"),
      ClgNames(firstname: "APOLLO INSTITUTE OF ENGINEERING &TECHNOLOGY AHMEDABAD", lastname: " "),
      ClgNames(firstname: "Arrdekta Inst. Of Technology, Khedbrahma, Sabarkantha", lastname: "http://www.arrdekta.org.in"),
      ClgNames(firstname: "Atmiya University, Faculty of Engineering and Technology,Rajkot" , lastname: "http://www.aits.edu.in"),
      ClgNames(firstname: "B.H.Gardi College Of Engg. & Technology , Rajkot", lastname: "http:gardividyapith.ac.in"),
      ClgNames(firstname: "Babaria Institute Of Technology,Varnama,Vadodara", lastname: " "),
      ClgNames(firstname: "Balaji Engineering College, Jnd-Dhoraji Highway, Makhiyala,Junagadh", lastname: " "),
      ClgNames(firstname: "Bhagwan Arihant Institute of Tech., Surat", lastname: "http:bmefcolleges.com"),
      ClgNames(firstname: "Bhagwan Mahavir College Of Engg. And Tech., Surat", lastname: " "),
      ClgNames(firstname: "Birla Vishvakarma Maha Vidhyalaya(Gia), V.V.Nagar", lastname: "http:bvmengineering.ac.in"),
      ClgNames(firstname: "Birla Vishvakarma Maha Vidhylaya(Sfi), V.V.Nagar", lastname: "http:bvmengineering.ac.in"),
      ClgNames(firstname: "C. K. Pithawala College Of Engg. & Tech., Surat", lastname: "http:ckpcet.ac.in"),
      ClgNames(firstname: "C.U.Shah College Of Engg.& Tech.,Wadhvan", lastname: "http:ccetvbt.org"),
      ClgNames(firstname: "Central Institue Of Plastics Engg. & Tech., Vatva,", lastname: "http:cipet.gov.in"),
      ClgNames(firstname: "Chandubhai S Patel Institute Of Technology, Changa", lastname: "http:charusat.ac.in"),
      ClgNames(firstname: "Chhotubhai Gopalbhai Patel Institute Of Tech., Tarsadi, Bardoli", lastname: "http:cgpit-bardoli.edu.in"),
      ClgNames(firstname: "D. A. Degree Engineering and Technology, Mahemdabad,Kheda", lastname: "https://www.dadet.in/"),
      ClgNames(firstname: "Darshan Institute Of Engg. & Tech., Rajkot-Morbi Highway,Hadala", lastname: "http:darshan.ac.in"),
      ClgNames(firstname: "Department of Engineering and Computing , Institute of Advance Research, Gandhinagar", lastname: "http://www.gecgh.cteguj.in/"),
      ClgNames(firstname: "Devang Patel Institute of Advance Technology And Research,Changa", lastname: "https://www.charusat.ac.in/depstar"),
      ClgNames(firstname: "Dhirubhai Ambani Institute of Info. & Comm. Tech., Gandhinagar", lastname: "https://www.daiict.ac.in/"),
      ClgNames(firstname: "Dr. Jivraj Mehta Institute Of Technology, Anand" , lastname: "http:djmit.ac.in"),
      ClgNames(firstname: "DR. S & S.S.Ghandhi Government Engineering College Surat", lastname: "http://www.ssgc.cteguj.in/"),
      ClgNames(firstname: "Dr. Subhahsh Technical Campus, Junagadh", lastname: "https://www.drsubhashtech.edu.in"),
      ClgNames(firstname: "Dr. V.R. Godhania College of Engg. & Tech., Porbandar", lastname: " "),
      ClgNames(firstname: "Engginering College, Tuwa, Godhara", lastname: "https://engtuwa.org/"),
      ClgNames(firstname: "Faculty Of Technology & Engineering(MSU), Vadodara", lastname: "https://www.msubaroda.ac.in/"),
      ClgNames(firstname: "Faculty Of Technology And Engineering(GIA), Dharmsinh Desai University, (DDU), Nadiad", lastname: "http:ddu.ac.in"),
      ClgNames(firstname: "Faculty Of Technology(Sfi), Dharmsinh Desai University, Nadiad" , lastname: "http:ddu.ac.in"),
      ClgNames(firstname: "G.H.Patel College Of Engg. & Tech. , V. V. Nagar", lastname: "http:gcet.ac.in"),
      ClgNames(firstname: "Gandhinagar Institute Of Technology, Moti Bhoyan, Kalol,Gandhinagar", lastname: "http:git.org.in"),
      ClgNames(firstname: "Ganpat University, Institute of Computer Tech., Kherva, Mehsana", lastname: "https://www.ict.gnu.ac.in/"),
      ClgNames(firstname: "GIDC Degree Engineering College, Abrama, Navsari" , lastname: " "),
      ClgNames(firstname: "Government Engineering College, Bharuch", lastname: "http:gecbharuch.com"),
      ClgNames(firstname: "Government Engineering College, Bhavnagar", lastname: " http:gecbvn.ac.in"),
      ClgNames(firstname: "Government Engineering College, Dahod", lastname: "http:gecdahod.org"),
      ClgNames(firstname: "Government Engineering College, Godhra", lastname: "http:gecgodhra.ac.in"),
      ClgNames(firstname: "Government Engineering College, Modasa", lastname: "http:gecmodasa.ac.in"),
      ClgNames(firstname: "Government Engineering College, Palanpur", lastname: "http:gecpalanpur.edu.in"),
      ClgNames(firstname: "Government Engineering College, Patan", lastname: "http:gecpatan.org"),
      ClgNames(firstname: "Government Engineering College, Rajkot", lastname: "http:gecrajkot.org"),
      ClgNames(firstname: "Government Engineering College, Sector 28 Gandhinagar", lastname: "http:gecg28.ac.in"),
      ClgNames(firstname: "Government Engineering College, Valsad", lastname: "http:gecvalsad.org"),
      ClgNames(firstname: "Grow More Faculty of Engineering, Berna, Himmatnagar", lastname: "http:growmore1.org"),
      ClgNames(firstname: "Gujarat Power Engg. And Res. Inst. (Gperi) (Ppp), Mevad,Mehsana", lastname: "http://gperi.ac.in/"),
      ClgNames(firstname: "GYANMANJARI INSTITUTE OF TECHNOLOGY Bhavnagar", lastname: " "),
      ClgNames(firstname: "Hansaba College Of Engieering And Technology, Siddhpur", lastname: " "),
      ClgNames(firstname: "Hasmukh Goswami College Of Engg, Vahelal", lastname: "http:hgce.org"),
      ClgNames(firstname: "Hjd Institute Of Technical Education And Reserch, Kera", lastname: "http:hjdinstitute.org"),
      ClgNames(firstname: "Indus Institute Of Tech. & Engg., Racharda, Ahmedabad", lastname: "http:indusuniversity.ac.in"),
      ClgNames(firstname: "Institute of Infrastructure,Technology,Research and Management(IITRAM),Ahmedabad", lastname: "https://iitram.ac.in/"),
      ClgNames(firstname: "Institute Of Technology, Nirma University Of Science & Technology, Ahmedabad", lastname: "https://nirmauni.ac.in/"),
      ClgNames(firstname: "Ipcowala Institute Of Engineering And Technology Dharmaj", lastname: "https://www.collegedekho.com/colleges/iiet-dharmaj"),
      ClgNames(firstname: "ITM Universe ( Institute of Technology & Management Universe)  Paladi, Halol Highway, Vadodara", lastname: "https://www.itm.ac.in/"),
      ClgNames(firstname: "K.J. Institute Of Engg. And Tech., Savali", lastname: "http:kjit.org"),
      ClgNames(firstname: "Kalol Institute Of Tech. & Research Center ,Kalol", lastname: "http:kirc-kalol.org"),
      ClgNames(firstname: "Kankeshwari Devi College of Engineering, Jamnagar", lastname: "http:kit.org.in"),
      ClgNames(firstname: "Knowledge Institute of Technology and Engineering, Bakrol, Anand" , lastname: "http://www.kitetech.ac.in/"),
      ClgNames(firstname: "L.D.College Of Engineering, Ahmedabad", lastname: "http://ldce.ac.in/"),
      ClgNames(firstname: "L.D.R.P. Institute Of Tech. & Research., Gandhinagar", lastname: "www.ldrp.ac.in"),
      ClgNames(firstname: "L.E.College ,Morbi", lastname: "http://www.lecm.cteguj.in/"),
      ClgNames(firstname: "L.J. Institute Of Engg And Tech., Ahmedabad", lastname: "http:ljinstitutes.org"),
      ClgNames(firstname: "Laljibhai Chaturbhai Institute Of Tech., Bhandu, Mahesana", lastname: "http:lcit.org"),
      ClgNames(firstname: "Laxmi Institute Of Technology, Sarigam, Valsad", lastname: "http:lvs.co.in"),
      ClgNames(firstname: "Madhuben & Bhanubhai Patel Institute of Technology, New V.V.Nagar" , lastname: "http:icctw.ac.in"),
      ClgNames(firstname: "Mahatma Gandhi Inst.Of Technical Edu. And Research Center,Navasari", lastname: "http:npvgiter.org"),
      ClgNames(firstname: "Mahavir Swami College Of Engineering & Technology,Bharthana-Vesu, Surat", lastname: " "),
      ClgNames(firstname: "Marwadi Edu. Foundation Group Of Institutions, Faculty Of Engg., Rajkot", lastname: "info@marwadieducation.edu.in"),
      ClgNames(firstname: "Merchant Engg. College, Basna. Visnagar", lastname: "http:mecbasna.ac.in"),
      ClgNames(firstname: "Narnarayan Shastri Institute of Technology, Jetalpur, Ahmedabad", lastname: "https://www.nsitgurukul.com/"),
      ClgNames(firstname: "Neotech Institute of Technology, Virod, Vadodara", lastname: "https://neotech.ac.in/"),
      ClgNames(firstname: "New L. J. Institute Of Engineering And Technology, Ahmedabad", lastname: "https://ljku.edu.in/"),
      ClgNames(firstname: "Noble Engineering College, Junagadh", lastname: "http:http:.org"),
      ClgNames(firstname: "Om Engineering College Junagadh", lastname: "www. Omeducation.edu.in"),
      ClgNames(firstname: "P.P. Savani School of Engineering, P.P. Savani University, Kosamba", lastname: "https://www.ppsu.ac.in/"),
      ClgNames(firstname: "Pacific School Of Engineering, Surat", lastname: "http:ominstitute.org"),
      ClgNames(firstname: "Pandit Deendayal Petroleum University ,Gandhinagar", lastname: "http://www.pdpu.ac.in/"),
      ClgNames(firstname: "Parul Institute of Engineering & Technology, Waghodia, Vadodara", lastname: "http:parul.ac.in"),
      ClgNames(firstname: "Prime Institute of Engineering and Technology, Jalalpore, Navsari", lastname: " "),
      ClgNames(firstname: "R.K. University - School of Engineering, Rajkot", lastname: "http:rku.ac.in"),
      ClgNames(firstname: "R.N.G. Patel Institute of Technology-RNGPIT (FETR),", lastname: "http://fetr.ac.in/"),
      ClgNames(firstname: "S.P.B. Patel Engg. College, (Saffrony), Linch, Mehsana", lastname: "http:saffrony.ac.in"),
      ClgNames(firstname: "S.S.AGRAWAL INSTITUTE OF ENGINEERING &TECHNOLOGY NAVSARI", lastname: "http://ssagrawal.org/ssaiet/department/computer/index.php"),
      ClgNames(firstname: "Sal College Of Engineering , Ahmedabad", lastname: "https://www.sal.edu.in/institutes/sal-college-of-engineering/"),
      ClgNames(firstname: "SAL ENGINEERING &TECHNICAL INSTITUTE, SOLA, AHMEDABAD", lastname: " "),
      ClgNames(firstname: "Samarth College Of Engineering & Technology, Himatnagar", lastname: "http:samarthcampus.com"),
      ClgNames(firstname: "Sanjaybhai Rajguru College of Engg. , Rajkot", lastname: "http:omshantiengg.org"),
      ClgNames(firstname: "Sankalchand  Patel College Of  Engg.,  Visnagar", lastname: "http:spcevng.ac.in"),
      ClgNames(firstname: "SARDAR PATEL COLLEGE OF ENGINEERING, BAKROL ANAND", lastname: "mctvisnagar@rediffmail.com"),
      ClgNames(firstname: "Sardar Vallabhbhai Patel Institute Of Tech.,Vasad", lastname: "http:svitvasad.ac.in"),
      ClgNames(firstname: "Sarvajanik College Of Engg. & Tech. , Surat", lastname: "http:scet.ac.in"),
      ClgNames(firstname: "School of Engg. & App. Sciences,Rai University,Dholka, Ahmedabad", lastname: "http:raiuniversity.edu.in"),
      ClgNames(firstname: "School of Engineering and Applied Science, Ahmedabad University, Ahmedabad", lastname: " "),
      ClgNames(firstname: "School of Engineering, Indrashil University, Kadi", lastname: "https://indrashiluniversity.edu.in/"),
      ClgNames(firstname: "SCHOOL OF SCIENCE & ENGINEERING., Navrachana University, Vadodara", lastname: "https://nuv.ac.in/"),
      ClgNames(firstname: "SCHOOL OF TECHNOLOGY, GSFC UNIVERSITY, VADODARA", lastname: "http://gtu-info.com/college/GSFCUNI/School-of-Technology-GSFC-University-Vadodara"),
      ClgNames(firstname: "Shankersinh Vaghela Bapu Institute Of Tech., Unava, Gandhinagar", lastname: "https://www.icbse.com/colleges/shankersinh-vaghela-bapu-institute-of-tech-unava-gandhina-kr2gy8"),
      ClgNames(firstname: "Shantilal Shah Engineering College ,Bhavnagar", lastname: "http://www.ssgec.ac.in/"),
      ClgNames(firstname: "SHREE SWAMINARAYAN INSTITUTE OF TECHNOLOGY, BHAT, GANDHINAGAR", lastname: "http://www.ssit.co.in/"),
      ClgNames(firstname: "Shri J M Sabva Institute Of Engineering And Technology, Botad", lastname: "http://gtu-info.com/college/JMSIET/J-M-Sabva-Botad-JMSIET"),
      ClgNames(firstname: "Shri Sadvidhya Mandal Institute Of Tech., Bharuch", lastname: "http:svmit.ac.in"),
      ClgNames(firstname: "Shri Satsangi Saketdham `Ram Ashram` Group Of Institutions, Vadasma", lastname: "http:satsangivadasma.org"),
      ClgNames(firstname: "Shri Sitaram N Patel Inst. Of Tech. & Res. (Vidhyabharti Trust), Umrakh", lastname: " "),
      ClgNames(firstname: "Shri Swami Atmanand Saraswati Institute Of Tech., Surat", lastname: "https://ssasit.ac.in/"),
      ClgNames(firstname: "Shroff S.R.Rotary Inst. Of Chemical Technology, Vatatia,Bharuch", lastname: "http://www.srict.in/"),
      ClgNames(firstname: "Sigma Institute Of Engg., Bakrol", lastname: "http:Sigma.ac.in"),
      ClgNames(firstname: "Silver Oak College Of Engg., & Tech. (WITHIN AMHEDABAD MUNICIPAL CORPORATION LIMIT), Ahmedabad", lastname: "http:socet.edu.in"),
      ClgNames(firstname: "Smt. S.R. Patel Engg. College, Dabhi, Unjha", lastname: "http:srpec.org.in"),
      ClgNames(firstname: "SMT. SHANTABEN HARIBHAI GAJERA ENGINEERINGCOLLEGE  Amreli", lastname: "http://www.shgec.org/"),
      ClgNames(firstname: "Swaminarayan College Of Engg. & Tech., Kalol", lastname: "http://gtu-info.com/College/Swaminarayan-College-Engineering-Technology-Kalol/Swaminarayan-College-Engineering-Technology-Kalol"),
      ClgNames(firstname: "Swarrnim Institute of Technology", lastname: "http://gtu-info.com/Diploma-Engineering/College/Swarnim-Gandhinagar"),
      ClgNames(firstname: "Tatva Institute Of Technological Studies, Modasa", lastname: "http:tatvafoundation.com"),
      ClgNames(firstname: "V.V.P. Engineering College, Rajkot", lastname: "http:vvpedulink.ac.in"),
      ClgNames(firstname: "Vadodara Institute of Engineering, Kotambi, Waghodiya, Vadodara", lastname: "http:vier.org.in"),
      ClgNames(firstname: "VEERAYATAN INSTITUTE OF ENGINEERING TECHNOLOGY & RESEARCH., Mandvi", lastname: "http:veereng.org"),
      ClgNames(firstname: "Vidhyadeep Institute of  Engineering & Technology, Anita(Kim), Surat", lastname: " "),
      ClgNames(firstname: "Vidush Somany Institute Of Tech. & Res., Kadi", lastname: "http://www.vsitr.ac.in/"),
      ClgNames(firstname: "Vishwakarma Government Engineering College, Chandkheda, Gandhinagar", lastname: "https://www.vgecg.ac.in/"),

    ];
  }
}